# Generated by Django 4.2.1 on 2023-05-10 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='CZK',
            field=models.IntegerField(default=0),
        ),
    ]
