# Generated by Django 4.1.7 on 2023-05-15 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0002_account_czk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='CZK',
            field=models.FloatField(default=0.0),
        ),
    ]
