# Generated by Django 4.1.7 on 2023-05-15 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_alter_transaction_amount_alter_transaction_currency_and_more'),
        ('authentification', '0003_alter_account_czk'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='history',
            field=models.ManyToManyField(blank=True, related_name='accounts', to='transaction.transaction'),
        ),
    ]
