# Generated by Django 4.1.7 on 2023-05-15 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='currency',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
